changed live view to use typescript
goutamvenkat/ClassMood pull request #54
Opened 2016-10-27 01:38 UTC by neilgoel

2016-10-29 15:11 UTC, nvohra3 commented
Looks good to me.

2016-10-29 19:55 UTC, goutamvenkat requested changes

2016-10-29 19:55 UTC, goutamvenkat commented on ClassMoodApp/static/js/controllers/ClassListController.js
> +            this.$window = $window;
why is this.window instantiated twice?

2016-10-29 19:55 UTC, goutamvenkat commented on ClassMoodApp/static/tsc/controllers/LiveViewController.ts
> +			this.lectureId = parseInt($("#lectureId").attr('lecture-id'), 10);
why is DOM manipulation used here?

2016-10-29 19:55 UTC, goutamvenkat commented on ClassMoodApp/templates/liveView.html
> +<div id="lectureId" lecture-id="{{lecture_id}}"></div>
I'm guessing you are using this lecture-id in you ts file. Use ng-model instead so that u don't have to reference this div by the attribute.

2016-10-30 01:37 UTC, neilgoel commented on ClassMoodApp/static/js/controllers/ClassListController.js
> +            this.$window = $window;
Removed the duplicate

2016-10-30 01:37 UTC, neilgoel commented on ClassMoodApp/templates/liveView.html
> +<div id="lectureId" lecture-id="{{lecture_id}}"></div>
Tried this but it isn't working

2016-10-30 01:37 UTC, neilgoel commented on ClassMoodApp/static/tsc/controllers/LiveViewController.ts
> +			this.lectureId = parseInt($("#lectureId").attr('lecture-id'), 10);
Same as below

2016-10-31 21:30 UTC, merged