DB Architecture and Clean Up
goutamvenkat/ClassMood pull request #55
Opened 2016-10-31 05:00 UTC by ZachPeterson

Added the new models for polling questions. Updated users to use a student vs non-student flag. Updated lecture system to separate out lectures and live lectures. Updated the api to include methods for creating a lecture. Updated the api live lecture methods to use live lecture information. Updated the controllers to call the correct live lecture methods and use the correct live lecture paramters. Tested new live lecture controller methods as well as initial data entered into the database using __init__.py

2016-10-31 14:35 UTC, krabagobanjo requested changes
Caught one thing, looks good otherwise. Changes appear to be propagating to the DB, but more extensive testing will come when the UI is built out anyway.

2016-10-31 14:35 UTC, krabagobanjo commented on ClassMoodApp/Models/API.py
> +            return ~user.is_student
'~' is a bitwise operator, and will return a number instead of a boolean.  Use 'not' instead

2016-10-31 18:00 UTC, ZachPeterson commented on ClassMoodApp/Models/API.py
> +            return ~user.is_student
Fixed in commit 5aec22d3c82e87020434e3ddc5c3e50ed5fea815

2016-11-01 06:57 UTC, nvohra3 approved these changes

2016-11-01 06:58 UTC, merged