Neilv sprint4
goutamvenkat/ClassMood pull request #59
Opened 2016-11-13 08:14 UTC by nvohra3

Pulled Kyle's branch and added features to view and add polling questions for a lecture when in the professor view.

2016-11-14 09:54 UTC, goutamvenkat commented
Site Crashed after I clicked add live lecture and then hit the home button

2016-11-14 10:08 UTC, goutamvenkat requested changes

2016-11-14 10:08 UTC, goutamvenkat commented on ClassMoodApp/static/tsc/controllers/CreatePollingQuestionController.ts
> +		let text = this.$scope.question_text;
Why is scope being used here? I'm using you are using ng-model and ng-controller for your html. If that's the case, there is no need to use scope. You can instead directly use the instance variables.

2016-11-14 10:08 UTC, goutamvenkat commented on ClassMoodApp/static/tsc/controllers/CreatePollingQuestionController.ts
> +						if (response.data) {
Preferably use === for strict equality comparison to bools. Javascript is a bit finicky with booleans.

2016-11-14 10:08 UTC, goutamvenkat commented on ClassMoodApp/static/tsc/controllers/LectureListController.ts
> +            this.$window.location.reload();
Do not use reload. Instead make an update function, as in this case, every time u call reload, the entire page has to reload. With an update function, only the table elements will change which will be quicker.

2016-11-14 10:08 UTC, goutamvenkat commented on ClassMoodApp/templates/createPollingQuestion.html
> +<nav class="navbar navbar-inverse navbar-top">
All new html pages will be extending from baseHomePage.html which all ready contains the navbar. This is a page I created, so after merging, ensure that your html is extending from that page, and change the block name to newPage.

2016-11-14 10:08 UTC, goutamvenkat commented on ClassMoodApp/templates/lectureList.html
> +<nav class="navbar navbar-inverse navbar-top">
Same thing as createPollingQuestion.html

2016-11-14 10:08 UTC, goutamvenkat commented on ClassMoodApp/templates/pollingQuestionList.html
> +<nav class="navbar navbar-inverse navbar-top">
Same thing as the above html.

2016-11-18 15:08 UTC, krabagobanjo requested changes
Just realized I didn't comment on this - I didn't find anything to add other than what Goutam found, and most of what he found pertained to my branch, which I changed.  Pulling the latest code from my branch will fix most of these.

Also, what was the error from when the site crashed?  I'd like to look in to that.

2016-11-18 17:03 UTC, nvohra3 commented on ClassMoodApp/static/tsc/app.ts
> +        .when("/pollingQuestionList/:class_id/:lecture_id", {
Should I just delete all of the entries in this file that relate to template rendering then?

2016-11-19 01:09 UTC, krabagobanjo approved these changes

2016-11-23 07:44 UTC, merged